# payload inertia parameters
mass: 0.300
inertia: {Ixx: 0.0145, Ixy: 0.0, Ixz: 0.0, Iyx: 0.0, Iyy: 0.0145, Iyz: 0.0, Izx: 0.0, Izy: 0.0, Izz: 0.0186}

# path to payload mesh
mesh_path: "package://RotorTM/mesh/fedex_box_24x24x18in.STL"